name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DH_REGISTRY: docker.io
      GH_REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      REPOSITORY: ${{ github.event.repository.name }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DH_REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.GH_REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - id: string
      name: Prepare GitHub Docker image name
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ env.IMAGE_NAME }}
    
    - name: Build and push
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: docker/build-push-action@v4
      with:
        target: deploy
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/${{ env.REPOSITORY }}:latest
          ${{ env.GH_REGISTRY }}/${{ steps.string.outputs.lowercase }}:latest
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        cache-from: type=gha,scope=${{ github.workflow }}
        cache-to: type=gha,mode=max,scope=${{ github.workflow }}
    
